projects:
    app:
        schemPath: schema.graphql
        extensions:
            endpoints:
            default: http://localhost:4000
    prisma:
        schemaPath: graphql/types/prisma/prisma.graphql
        extensions:
            prisma: prisma.yml